---
# handlers file for tester
- name: restart bind
  service:
    name: named
    state: restarted

- name: restart haproxy
  service:
    name: haproxy
    state: restarted

- name: restart dhcpd
  service:
    name: dhcpd
    state: restarted

- name: restart tftp
  service:
    name: tftp
    state: restarted

- name: reload sshd
  service:
    name: sshd
    state: reloaded

- name: restart chronyd
  service:
    name: chronyd
    state: restarted

- name: restart NetworkManager
  service:
    name: NetworkManager
    state: restarted
